<?php

/* ****************************************************************************
 * Copyright 2026 51 Degrees Mobile Experts Limited (51degrees.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 * ***************************************************************************/

declare(strict_types=1);

namespace SwanCommunity\Owid;

use DateTimeImmutable;

/**
 * OWID structure which can be used as a node in a tree.
 *
 * An OWID records that the processor operating the domain handled the payload,
 * and any other OWIDs covered by the signature, at the date and time given. It
 * is only worth anything because it is signed, so a caller cannot build one.
 * An instance arrives by exactly two routes, either from reading bytes that
 * were already a complete OWID, with tryFromBase64, tryFromByteArray or
 * tryFromFrame, or from a Creator that signs one into existence with
 * Creator::create. There is deliberately no way to assemble a half made one,
 * because an unsigned OWID is indistinguishable from a signed one to the code
 * downstream of it, and the difference only surfaces later when a verification
 * fails somewhere nobody is watching.
 *
 * The fields are read only for the same reason. A parsed OWID's signature
 * covers its fields as they arrived, so a caller that could change one would
 * hold something whose signature no longer describes it. PHP strings are
 * values rather than references, so what a caller does with a copy of the
 * payload or the signature cannot reach the OWID it came from.
 *
 * The payload and signature are held as raw byte strings because PHP strings
 * are byte arrays.
 */
final class Owid
{
    /**
     * Built by the two routes above and by nothing else. PHP has no package
     * private, so a private constructor, with the parse and creation code
     * inside this class, is the strongest boundary the language offers, and it
     * is enforced by the engine rather than by a check that runs at run time.
     */
    private function __construct(
        /** The byte version of the OWID. */
        public readonly Version $version,
        /** Domain associated with the creator. */
        public readonly string $domain,
        /** The date and time to the nearest minute in UTC of the creation. */
        public readonly DateTimeImmutable $date,
        /** Raw bytes that form the payload. */
        public readonly string $payload,
        /**
         * Signature for this OWID and any others provided when signing.
         * Generated by the Creator and held as 64 raw bytes.
         */
        public readonly string $signature
    ) {
    }

    /**
     * Reads a complete OWID from its base 64 form, answering rather than
     * raising when the value is not one.
     *
     * The value may be anything at all, because this is external data and
     * failing to be an OWID is an ordinary outcome. Input with or without the
     * trailing padding is accepted, as an OWID is carried both ways. The
     * marker for an absent OWID is refused here as it is on the byte array
     * surface.
     *
     * @param mixed $value the base 64 text, or anything a caller was handed
     */
    public static function tryFromBase64(mixed $value): ParseResult
    {
        if ($value === null || $value === '') {
            return ParseResult::failed(ParseStatus::MissingInput);
        }
        if (!is_string($value)) {
            // A repeated query parameter with brackets reaches a PHP
            // application as an array, so a caller passing on what it was
            // given is not necessarily passing on a string.
            return ParseResult::failed(ParseStatus::InvalidInputType);
        }
        // A base 64 string is four characters for every three bytes, so a
        // length that leaves one character over encodes no whole byte and
        // cannot have come from an encoder.
        if (strlen($value) % 4 === 1) {
            return ParseResult::failed(ParseStatus::InvalidBase64);
        }
        $buffer = base64_decode($value, true);
        if ($buffer === false) {
            return ParseResult::failed(ParseStatus::InvalidBase64);
        }
        return self::parse($buffer, 0, true);
    }

    /**
     * Reads a complete OWID from a buffer holding exactly one.
     *
     * The buffer must be one whole OWID and nothing else, so bytes after the
     * envelope are refused, because on this surface there is nothing else they
     * could belong to. The marker for an absent OWID, a single zero byte, is
     * refused as well, because it carries no signature and only means anything
     * inside a framed buffer.
     *
     * @param mixed $buffer the raw bytes, or anything a caller was handed
     */
    public static function tryFromByteArray(mixed $buffer): ParseResult
    {
        if ($buffer === null || $buffer === '') {
            return ParseResult::failed(ParseStatus::MissingInput);
        }
        if (!is_string($buffer)) {
            return ParseResult::failed(ParseStatus::InvalidInputType);
        }
        return self::parse($buffer, 0, true);
    }

    /**
     * Reads one OWID from a buffer that may carry more after it, starting at
     * the offset given.
     *
     * Used where several OWIDs are framed one after another. Bytes following
     * the signature are left alone, because they may be the next envelope
     * rather than rubbish, and the number of bytes this one occupied is
     * reported as the consumed field of the result so a caller can advance to
     * the next.
     *
     * This is the one surface that reports the marker for an absent OWID,
     * because a frame that holds one is saying an optional OWID is not there,
     * which a caller walking the frames has to be able to tell from a frame
     * that is malformed.
     */
    public static function tryFromFrame(string $buffer, int $offset = 0): ParseResult
    {
        if ($offset < 0 || $offset >= strlen($buffer)) {
            return ParseResult::failed(ParseStatus::MissingInput);
        }
        return self::parse($buffer, $offset, false);
    }

    /**
     * Reads the fields of one OWID from the buffer, starting at the offset
     * given, and reports what was found.
     *
     * The buffer is walked by index and every read is checked against what is
     * left, so a malformed envelope is a comparison that fails rather than an
     * exception that is built and unwound. That matters because the data comes
     * from outside, and whoever sends it chooses how often this fails and how
     * large each attempt is.
     *
     * When exact is true the envelope must end where the buffer does, and when
     * it is false anything after the signature is left for the caller.
     */
    private static function parse(
        string $buffer,
        int $offset,
        bool $exact
    ): ParseResult {
        $total = strlen($buffer);
        $at = $offset;
        if ($at >= $total) {
            // Nothing was supplied, which is not the same as data that
            // stopped part way through a field.
            return ParseResult::failed(ParseStatus::MissingInput);
        }

        $version = Version::tryFrom(ord($buffer[$at]));
        if ($version === null) {
            return ParseResult::failed(ParseStatus::UnsupportedVersion);
        }
        $at += 1;

        if ($version === Version::Empty) {
            // The marker for an OWID that is not present carries no domain,
            // date, payload or signature, so it can never verify, and handing
            // one to a caller would be the single case of an instance with no
            // signature reaching calling code, which is what the construction
            // boundary exists to prevent. A whole buffer holding only the
            // marker is therefore refused. It remains meaningful inside a
            // framed buffer, where it stands for an optional OWID that is
            // absent, so a framed read still reports it and consumes its one
            // byte.
            if ($exact) {
                return ParseResult::failed(ParseStatus::UnsupportedVersion);
            }
            return ParseResult::parsed(
                new self($version, '', Io::baseDate(), '', ''),
                $at - $offset
            );
        }

        // The domain, terminated by a zero byte. Nothing declares its length,
        // and the terminator is whatever the sender wrote, so the search for
        // it stops at the greatest number of characters a domain name can hold
        // rather than running to the end of the buffer. strcspn takes the
        // window as an argument and so examines no more bytes than the window.
        $maximum = OwidException::MAXIMUM_DOMAIN_LENGTH;
        $count = strcspn($buffer, "\0", $at, $maximum + 1);
        if ($count > $maximum) {
            return ParseResult::failed(ParseStatus::InvalidDomainEncoding);
        }
        if ($at + $count >= $total) {
            // The buffer ran out inside the domain, which is data that merely
            // stopped rather than a domain that cannot be valid.
            return ParseResult::failed(ParseStatus::UnexpectedEnd);
        }
        $domain = substr($buffer, $at, $count);
        $at += $count + 1;

        // The date, whose width depends on the version.
        if ($version === Version::Version1) {
            if ($total - $at < 2) {
                return ParseResult::failed(ParseStatus::UnexpectedEnd);
            }
            $hours = (ord($buffer[$at]) << 8) | ord($buffer[$at + 1]);
            $at += 2;
            $date = Io::baseDate()->modify('+' . $hours . ' hours');
        } else {
            if ($total - $at < 4) {
                return ParseResult::failed(ParseStatus::UnexpectedEnd);
            }
            $minutes = self::uint32($buffer, $at);
            $at += 4;
            $date = Io::baseDate()->modify(
                '+' . sprintf('%.0F', $minutes) . ' minutes'
            );
        }
        if ($date === false) {
            // Only a date the calendar cannot express reaches this, which the
            // four byte minute count of versions 2 and 3 cannot reach, so it
            // guards a runtime whose date range is narrower than the format's.
            return ParseResult::failed(ParseStatus::MalformedEnvelope);
        }

        if ($total - $at < 4) {
            return ParseResult::failed(ParseStatus::UnexpectedEnd);
        }
        $declared = self::uint32($buffer, $at);
        $at += 4;

        // The declaration is the sender's claim about a payload not yet read,
        // so it is compared with what is actually present before anything is
        // sized by it.
        if ($exact) {
            // Computed signed, so a buffer with fewer bytes left than a
            // signature needs gives a negative count rather than wrapping, and
            // a negative count can never equal a declaration. The disagreement
            // is the finding even when the buffer also stopped early, because
            // what a reader can say for certain is that the declared payload
            // cannot leave exactly the signature the version requires, and
            // that is true whichever way the bytes fall short. The comparison
            // is numeric rather than identical because on a 32 bit runtime the
            // declaration is a float once it passes the integer range.
            $present = ($total - $at) - OwidException::SIGNATURE_LENGTH;
            if ($present != $declared) {
                return ParseResult::failed(ParseStatus::ByteCountMismatch);
            }
        } else {
            // A framed reader cannot call the following bytes trailing
            // rubbish, because they may be the next envelope, so all it can
            // require is that this envelope is complete. Anything less is data
            // that stopped early.
            $available = ($total - $at) - OwidException::SIGNATURE_LENGTH;
            if ($available < $declared) {
                return ParseResult::failed(ParseStatus::UnexpectedEnd);
            }
        }

        // The bytes are all here. Whether this runtime can hold them as one
        // string is a separate question with a different answer, because the
        // same envelope may be readable elsewhere. The declaration is an
        // integer unless it passed the integer range, which only a 32 bit
        // build can do.
        if (!is_int($declared)) {
            return ParseResult::failed(
                ParseStatus::ImplementationCapacityExceeded
            );
        }

        $payload = substr($buffer, $at, $declared);
        $at += $declared;
        $signature = substr($buffer, $at, OwidException::SIGNATURE_LENGTH);
        $at += OwidException::SIGNATURE_LENGTH;

        if ($exact && $at !== $total) {
            // Unreachable while the count check above holds, and kept so that
            // a future change to that arithmetic cannot silently start
            // accepting bytes after the envelope.
            return ParseResult::failed(ParseStatus::MalformedEnvelope);
        }

        return ParseResult::parsed(
            new self($version, $domain, $date, $payload, $signature),
            $at - $offset
        );
    }

    /**
     * Reads the four byte little endian unsigned length at the offset given.
     *
     * The value is composed from the bytes rather than unpacked so that it is
     * exact on a 32 bit runtime, where the top byte can carry it past the
     * integer range. PHP widens the result to a float there, which holds every
     * value the field can express without loss, so the comparison with the
     * bytes present is made before anything narrows the declaration to
     * something allocatable.
     *
     * @return int|float the declared count, a float only where it exceeds what
     *                   an integer on this runtime can hold
     */
    private static function uint32(string $buffer, int $at): int|float
    {
        $low = ord($buffer[$at])
            | (ord($buffer[$at + 1]) << 8)
            | (ord($buffer[$at + 2]) << 16);
        return $low + (ord($buffer[$at + 3]) * 16777216);
    }

    /**
     * Creates and signs a new OWID for the creator, carrying the payload given
     * and covering any others given.
     *
     * This is one of only two ways an OWID reaches calling code, the other
     * being a successful parse. The creator owns the version, the domain, the
     * date and the signature, and the caller supplies the payload, so there is
     * no moment at which a partly built OWID exists for anyone to hold or pass
     * on. The signature is calculated before the instance exists, which is why
     * this lives here rather than on Creator, as a private constructor can only
     * be reached from inside this class.
     *
     * @param array<int, Owid> $others covered by the signature, and required
     *                                 in the same order when verifying
     *
     * @throws OwidException when the fields can not be encoded or the signing
     *                       operation fails.
     *
     * @internal Callers use Creator::create, which is the public spelling.
     */
    public static function createSignedBy(
        Creator $creator,
        string $payload,
        array $others = []
    ): self {
        $version = Version::default();
        $domain = $creator->domain();
        $date = new DateTimeImmutable('now');
        $data = '';
        self::writeFieldsNoSignature($data, $version, $domain, $date, $payload);
        foreach ($others as $other) {
            $other->toBuffer($data);
        }
        $signature = $creator->crypto()->signByteArray($data);
        if (strlen($signature) !== OwidException::SIGNATURE_LENGTH) {
            throw OwidException::invalidSignatureLength(strlen($signature));
        }
        return new self($version, $domain, $date, $payload, $signature);
    }

    /**
     * Returns the OWID as a byte array.
     *
     * @throws OwidException when the fields can not be encoded.
     */
    public function asByteArray(): string
    {
        $buffer = '';
        $this->toBuffer($buffer);
        return $buffer;
    }

    /**
     * Returns the OWID as a base 64 encoded string with padding.
     *
     * @throws OwidException when the OWID can not be serialized.
     */
    public function asBase64(): string
    {
        return base64_encode($this->asByteArray());
    }

    /**
     * Appends the OWID, including the signature, to the buffer provided.
     *
     * @throws OwidException when the OWID can not be serialized.
     */
    public function toBuffer(string &$buffer): void
    {
        $this->toBufferNoSignature($buffer);
        Io::writeSignature($buffer, $this->signature);
    }

    /**
     * Appends an empty OWID marker to the buffer. Used to indicate optional
     * OWIDs in byte arrays.
     */
    public static function emptyToBuffer(string &$buffer): void
    {
        Io::writeByte($buffer, Version::Empty->asByte());
    }

    /**
     * Appends the fields other than the signature to the buffer. This is the
     * data over which the signature is calculated.
     *
     * @throws OwidException when the fields can not be encoded.
     */
    public function toBufferNoSignature(string &$buffer): void
    {
        self::writeFieldsNoSignature(
            $buffer,
            $this->version,
            $this->domain,
            $this->date,
            $this->payload
        );
    }

    /**
     * Appends the fields other than the signature to the buffer. Static so
     * that creation can build the data to sign before an instance exists.
     *
     * @throws OwidException when the fields can not be encoded.
     */
    private static function writeFieldsNoSignature(
        string &$buffer,
        Version $version,
        string $domain,
        DateTimeImmutable $date,
        string $payload
    ): void {
        Io::writeByte($buffer, $version->asByte());
        Io::writeString($buffer, $domain);
        Io::writeDate($buffer, $date, $version);
        Io::writeByteArray($buffer, $payload);
    }

    /**
     * Builds the byte array used for signing and verification. Contains the
     * fields of this OWID without the signature, followed by the complete byte
     * form of each of the others in the order provided.
     *
     * @param array<int, Owid> $others
     *
     * @throws OwidException when the fields can not be encoded.
     */
    public function dataForCrypto(array $others = []): string
    {
        $buffer = '';
        $this->toBufferNoSignature($buffer);
        foreach ($others as $other) {
            $other->toBuffer($buffer);
        }
        return $buffer;
    }

    /**
     * The payload interpreted as a string of raw bytes. The payload is treated
     * as UTF-8 text by callers, but no transformation is applied here.
     */
    public function payloadAsString(): string
    {
        return $this->payload;
    }

    /**
     * The payload as lower case hexadecimal for display purposes, with no
     * separator. For example the bytes 0x01 0x03 become "0103".
     */
    public function payloadAsPrintable(): string
    {
        return bin2hex($this->payload);
    }

    /**
     * The payload as a base 64 encoded string with padding.
     */
    public function payloadAsBase64(): string
    {
        return base64_encode($this->payload);
    }

    /**
     * Returns the number of complete minutes that have elapsed since the OWID
     * was created. The granularity is to the nearest minute.
     */
    public function ageMinutes(): int
    {
        $now = new DateTimeImmutable('now');
        return intdiv($now->getTimestamp() - $this->date->getTimestamp(), 60);
    }

    /**
     * Verifies this OWID, and any others that were included when it was
     * signed, using the crypto instance provided. Pass an empty array for
     * others when the OWID was signed on its own.
     *
     * @param array<int, Owid> $others
     *
     * @throws OwidException when the crypto instance can not verify or the
     *                       fields can not be encoded.
     */
    public function verifyWithCrypto(Crypto $crypto, array $others = []): bool
    {
        $data = $this->dataForCrypto($others);
        return $crypto->verifyByteArray($data, $this->signature);
    }

    /**
     * Verifies this OWID, and any others that were included when it was
     * signed, using the public key in SPKI PEM form provided.
     *
     * @param array<int, Owid> $others
     *
     * @throws OwidException when the PEM is not a valid public key or the
     *                       fields can not be encoded.
     */
    public function verifyWithPublicKey(string $publicPem, array $others = []): bool
    {
        $crypto = Crypto::newVerifyOnly($publicPem);
        return $this->verifyWithCrypto($crypto, $others);
    }

    /**
     * Says whether the signature is genuine, and where it could not be
     * checked, says that instead of reporting a forgery.
     *
     * A key that cannot be read is InvalidKey and never SignatureInvalid,
     * because the identifier may be perfectly good and only the key material
     * wrong. Use this in preference to verifyWithPublicKey wherever the
     * difference between "does not match" and "could not be checked" changes
     * what the caller should do.
     *
     * @param array<int, Owid> $others
     */
    public function signatureStatus(
        string $publicPem,
        array $others = []
    ): SignatureStatus {
        $crypto = Crypto::tryVerifyOnly($publicPem);
        if ($crypto === null) {
            return SignatureStatus::InvalidKey;
        }
        return $this->signatureStatusWithCrypto($crypto, $others);
    }

    /**
     * Says whether the signature is genuine using the crypto instance
     * provided, with the same separation between a signature that does not
     * match and a check that could not be made.
     *
     * @param array<int, Owid> $others
     */
    public function signatureStatusWithCrypto(
        Crypto $crypto,
        array $others = []
    ): SignatureStatus {
        try {
            $data = $this->dataForCrypto($others);
        } catch (OwidException $e) {
            // The fields of this OWID always encode, because it was parsed or
            // created, so only an other that cannot be encoded reaches this.
            return SignatureStatus::VerificationError;
        }
        return $crypto->signatureStatus($data, $this->signature);
    }

    /**
     * Returns the OWID as a base 64 string, the same as asBase64. Used when an
     * OWID is converted to a string.
     *
     * @throws OwidException when the OWID can not be serialized.
     */
    public function __toString(): string
    {
        return $this->asBase64();
    }
}
